typography_spectrum: 1
color:
  brandColors:
    - '#0d0d0b'
    - '#3d3020'
    - '#5f4b33'
    - '#8f7658'
    - '#b69979'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25613
analytics:
  google: null
  facebook: null
  twitter: null
name: dubestephane
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Stephane Dube, webdesigner'
description: Toujours l√† pour vous !
purpose: []
